{
 "title": "BTC: Number of txns, total fee per block, volume",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Total Fee (in mBTC)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"total_fee\" / 100000) \n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Total fee (144blk avg)\",\n  avg(\"total_fee\" / 100000) \n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"Total fee (12blk avg)\" \nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Transactions per block",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"num_txs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Number of transactions(144blk avg)\",\n  avg(\"num_txs\")\n    OVER(ORDER BY time ROWS BETWEEN 25 PRECEDING AND CURRENT ROW) AS \"Number of transactions(25 blk avg)\"\nFROM dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Block Size (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"total_block_size\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Block size (144blk avg)\",\n  avg(\"total_block_size\")\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"Block size (12blk avg)\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Block Weight (moving average)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"total_weight\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Block size (144blk avg)\",\n  avg(\"total_weight\")\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"Block size (12blk avg)\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Volume (BTC)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"total_amount_out\" / 1000000)\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Volume (144blk avg)\",\n  avg(\"total_amount_out\" / 1000000)\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"Volume (12blk avg)\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  }
 ]
}