{
 "title": "Consolidation Metrics (Individual Blocks)",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "About",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "content": "# Consolidations\nA transaction is considered a consolidating transaction if it has at least 3 inputs.\n\n\"MTO\" stands for many-to-one. It refers to transactions that have many inputs (at least 3) and exactly one output. This is a stricter definition of consolidation."
  },
  {
   "title": "MTO Consolidating Transactions and outputs",
   "type": "graph",
   "description": "MTO transaction = transaction with at least 3 inputs and exactly 1 output",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  \"mto_output_count\" AS \"MTO outputs (12 blk avg)\",\n  \"mto_consolidations\"AS \"MTO txs (12 blk avg)\"\nFROM\n  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Consolidating Transactions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"consolidating_txs\") as \"Number of consolidating transactions\"\nFROM\n  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Outputs Consolidated",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"outputs_consolidated\") as \"Number of outputs consolidated\"\nFROM\n  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Percent of Outputs Consolidated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n   $__time(\"time\"),\n  avg(\"percent_inputs_consolidated\") as \"Percent of Outputs Consolidated\"\nFROM\n  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Percent of Outputs in Block Consolidated",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  \"percent_inputs_consolidated\" AS  \"Percent of Outputs Consolidated\",\n   cast(\"mto_output_count\" as decimal) / cast(NULLIF(\"num_inputs\", 0) as decimal) AS  \"Percent of Outputs in MTO Consolidations\"\nFROM\n  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  }
 ]
}