{
 "title": "Fee Rate Comparison",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Fee Rate Comparison (individual blocks) in satoshis/vbyte",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  \"feerate_percentiles\"[1] AS \"10th percentile fee rate\",\n  \"feerate_percentiles\"[2] AS \"25th percentile fee rate\",\n  \"feerate_percentiles\"[3] AS \"50th percentile fee rate\",\n  \"feerate_percentiles\"[4] AS \"75th percentile fee rate\",\n  \"feerate_percentiles\"[5] AS \"90th percentile fee rate\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fee Rate Comparison (12 block  average) in satoshis/vbyte",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"feerate_percentiles\"[1])\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"10th percentile fee rate (12blk avg)\",\n  avg(\"feerate_percentiles\"[2])\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"25th percentile fee rate (12blk avg)\",\n  avg(\"feerate_percentiles\"[3])\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"50th percentile fee rate (12blk avg)\",\n  avg(\"feerate_percentiles\"[4])\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"75th percentile fee rate (12blk avg)\",\n  avg(\"feerate_percentiles\"[5])\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"90th percentile fee rate (12blk avg)\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fee Rate Comparison (144 block  average) in satoshis/vbyte",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"feerate_percentiles\"[1])\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"10th percentile fee rate (144blk avg)\",\n  avg(\"feerate_percentiles\"[2])\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"25th percentile fee rate (144blk avg)\",\n  avg(\"feerate_percentiles\"[3])\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"50th percentile fee rate (144blk avg)\",\n  avg(\"feerate_percentiles\"[4])\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"75th percentile fee rate (144blk avg)\",\n  avg(\"feerate_percentiles\"[5])\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"90th percentile fee rate (144blk avg)\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fee Rate Comparison (per block) in satoshis/vbyte",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  \"feerate_percentiles\"[1] \"10th percentile fee rate\",\n  \"feerate_percentiles\"[2] AS \"25th percentile fee rate\",\n  \"feerate_percentiles\"[3] AS \"50th percentile fee rate\",\n  \"feerate_percentiles\"[4] AS \"75th percentile fee rate\",\n  \"feerate_percentiles\"[5] AS \"90th percentile fee rate\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  }
 ]
}