{
 "title": "SegWit Usage (Individual Blocks)",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Transactions spending from SegWit outputs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n   $__time(\"time\"), \n  \"percent_txs_spending_native_p2wpkh_outputs\" AS \"Txs Spending Native P2WPKH Outputs\",\n  \"percent_txs_spending_nested_p2wpkh_outputs\" AS \"Txs Spending Nested P2WPKH Outputs\",\n  \"percent_txs_spending_native_p2wsh_outputs\" AS \"Txs Spending Native P2WSH Outputs\",\n  \"percent_txs_spending_nested_p2wsh_outputs\" AS \"Txs Spending Nested P2WSH Outputs\",\n  \"percent_txs_that_are_segwit_txs\" AS \"SegWit Txs\" \nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "SegWit Outputs spent",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  \"native_p2wpkh_outputs_spent\" AS \"Native P2WPKH Outputs Spent\",\n  \"nested_p2wpkh_outputs_spent\" AS \"Nested P2WPKH Outputs Spent\",\n  \"native_p2wsh_outputs_spent\" AS \"Native P2WSH Outputs Spent\",\n  \"nested_p2wsh_outputs_spent\" AS \"Nested P2WSH Outputs Spent\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Transactions creating SegWit Outputs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "12h" ], "type": "time" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n    $__time(\"time\"),\n  \"txs_creating_p2wpkh\" AS \"Num Txs Creating P2WPKH outputs\",\n  \"txs_creating_p2wsh\" AS \"Num Txs Creating P2WSH outputs\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "SegWit Outputs Created",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  \"new_p2wpkh_outputs\" AS \"Num New P2WPKH Outputs\",\n  \"new_p2wsh_outputs\" AS \"Num New P2WSH Outputs\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  }
 ]
}