{
 "title": "SegWit Usage Trends",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Percentage of  Transactions spending Nested vs. Native Outputs (144 block avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"), \n  avg(\"percent_txs_spending_nested_segwit_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Txs spending Nested SW Outputs\",\n  avg(\"percent_txs_spending_native_segwit_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Txs spending Native SW Outputs\",\n  avg(\"percent_txs_that_are_segwit_txs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"SegWit Transactions\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Percentage of  Transactions spending Nested vs. Native Outputs (12 block avg)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"percent_txs_spending_nested_segwit_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"Txs spending Nested SW Outputs\",\n  avg(\"percent_txs_spending_native_segwit_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"Txs spending Native SW Outputs\",\n  avg(\"percent_txs_that_are_segwit_txs\")\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"SegWit Transactions\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Transactions creating SegWit Outputs (144 block average)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "12h" ], "type": "time" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"txs_creating_p2wpkh\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Num Txs Creating P2WPKH outputs\",\n  avg(\"txs_creating_p2wsh\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Num Txs Creating P2WSH outputs\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "SegWit Outputs spent (144 block avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"native_p2wpkh_outputs_spent\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Native P2WPKH Outputs Spent\",\n  avg(\"nested_p2wpkh_outputs_spent\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Nested P2WPKH Outputs Spent\",\n  avg(\"native_p2wsh_outputs_spent\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Native P2WSH Outputs Spent\",\n  avg(\"nested_p2wsh_outputs_spent\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Nested P2WSH Outputs Spent\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "SegWit Outputs Created (144 block avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"new_p2wpkh_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Num New P2WPKH Outputs\",\n  avg(\"new_p2wsh_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Num New P2WSH Outputs\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Transactions spending from SegWit output (144 block avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"percent_txs_spending_native_p2wpkh_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Txs Spending Native P2WPKH Outputs\",\n  avg(\"percent_txs_spending_nested_p2wpkh_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Txs Spending Nested P2WPKH Outputs\",\n  avg(\"percent_txs_spending_native_p2wsh_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Txs Spending Native P2WSH Outputs\",\n  avg(\"percent_txs_spending_nested_p2wsh_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Txs Spending Nested P2WSH Outputs\",\n  avg(\"percent_txs_that_are_segwit_txs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"SegWit Txs\" \nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "Percentage of Inputs spending from SegWit output (144 block avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block_metrics",
     "rawSql": "SELECT\n    $__time(\"time\"),\n  avg(\"percent_of_inputs_spending_p2wpkh_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Inputs spending P2WPKH outputs\",\n  avg(\"percent_of_inputs_spending_p2wsh_outputs\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"Inputs spending P2WSH outputs\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  }
 ]
}