{
 "title": "UTXO Set Changes",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "UTXO Set Change (144 block and 12 block avg)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "Number of outputs" }
   ],
   "targets": [
    {
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"utxo_increase\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"UTXO Increase (144 blk avg)\",\n  avg(\"utxo_increase\")\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"UTXO Increase (12 blk avg)\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "UTXO Set Change",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Number of outputs" }
   ],
   "targets": [
    {
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  \"utxo_increase\" as \"UTXO Increase\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "UTXO Set Size Change  (144 block and 13 block avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes", "label": "Number of outputs" }
   ],
   "targets": [
    {
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  avg(\"utxo_size_increase\")\n    OVER(ORDER BY time ROWS BETWEEN 144 PRECEDING AND CURRENT ROW) AS \"UTXO Set Size Increase (144 blk avg)\",\n  avg(\"utxo_size_increase\")\n    OVER(ORDER BY time ROWS BETWEEN 12 PRECEDING AND CURRENT ROW) AS \"UTXO Set Size Increase (12 blk avg)\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  },
  {
   "title": "UTXO Set Size Change  (144 block and 13 block avg)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes", "label": "Number of outputs" }
   ],
   "targets": [
    {
     "measurement": "block_metrics",
     "rawSql": "SELECT\n  $__time(\"time\"),\n  \"utxo_size_increase\" as \"UTXO Set Size increase\"\nFROM  dashboard_data_v2\nWHERE\n  $__unixEpochFilter(\"time\")\nORDER BY time"
    }
   ]
  }
 ]
}